# This workflow will build a golang project

name: Go

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64, arm64, arm]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    - name: Build on ${{matrix.GOARCH}} for ${{matrix.GOOS}}
      run: GOOS=${{matrix.GOOS}} GOARCH=${{matrix.GOARCH}} go build
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: binary-${{ matrix.GOARCH }}-${{ matrix.GOOS }}
        path: |
          ytstats.exe
          ytstats
