name: Make release

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - name: Build files
      run: |
        CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags '-extldflags "-static"' -o ytstats.exe
        zip ytstats_${{ github.event.release.tag_name }}_Windows-64bit.zip ytstats.exe
        CGO_ENABLED=0 GOOS=windows GOARCH=arm go build -ldflags '-extldflags "-static"' -o ytstats.exe
        zip ytstats_${{ github.event.release.tag_name }}_Windows-ARM.zip ytstats.exe
        CGO_ENABLED=0 GOOS=windows GOARCH=arm64 go build -ldflags '-extldflags "-static"' -o ytstats.exe
        zip ytstats_${{ github.event.release.tag_name }}_Windows-ARM64.zip ytstats.exe
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags '-extldflags "-static"' -o ytstats
        tar -czvf ytstats_${{ github.event.release.tag_name }}_Linux-64bit.tar.gz ytstats
        CGO_ENABLED=0 GOOS=linux GOARCH=386 go build -ldflags '-extldflags "-static"' -o ytstats
        tar -czvf ytstats_${{ github.event.release.tag_name }}_Linux-32bit.tar.gz ytstats
        CGO_ENABLED=0 GOOS=linux GOARCH=arm go build -ldflags '-extldflags "-static"' -o ytstats
        tar -czvf ytstats_${{ github.event.release.tag_name }}_Linux-ARM.tar.gz ytstats
        CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -ldflags '-extldflags "-static"' -o ytstats
        tar -czvf ytstats_${{ github.event.release.tag_name }}_Linux-ARM64.tar.gz ytstats
        CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags '-s -extldflags "-sectcreate __TEXT __info_plist Info.plist"' -o ytstats
        tar -czvf ytstats_${{ github.event.release.tag_name }}_macOS-64bit.tar.gz ytstats
        CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -ldflags '-s -extldflags "-sectcreate __TEXT __info_plist Info.plist"' -o ytstats
        tar -czvf ytstats_${{ github.event.release.tag_name }}_macOS-ARM64.tar.gz ytstats
    - name: Create checksums.txt
      run: |
        touch ytstats_${{ github.event.release.tag_name }}_checksums.txt
        sha256sum ytstats_${{ github.event.release.tag_name }}_Windows-64bit.zip >> ytstats_${{ github.event.release.tag_name }}_checksums.txt
        sha256sum ytstats_${{ github.event.release.tag_name }}_Windows-ARM.zip >> ytstats_${{ github.event.release.tag_name }}_checksums.txt
        sha256sum ytstats_${{ github.event.release.tag_name }}_Windows-ARM64.zip >> ytstats_${{ github.event.release.tag_name }}_checksums.txt
        sha256sum ytstats_${{ github.event.release.tag_name }}_Linux-64bit.tar.gz >> ytstats_${{ github.event.release.tag_name }}_checksums.txt
        sha256sum ytstats_${{ github.event.release.tag_name }}_Linux-32bit.tar.gz >> ytstats_${{ github.event.release.tag_name }}_checksums.txt
        sha256sum ytstats_${{ github.event.release.tag_name }}_Linux-ARM.tar.gz >> ytstats_${{ github.event.release.tag_name }}_checksums.txt
        sha256sum ytstats_${{ github.event.release.tag_name }}_Linux-ARM64.tar.gz >> ytstats_${{ github.event.release.tag_name }}_checksums.txt
        sha256sum ytstats_${{ github.event.release.tag_name }}_macOS-64bit.tar.gz >> ytstats_${{ github.event.release.tag_name }}_checksums.txt
        sha256sum ytstats_${{ github.event.release.tag_name }}_macOS-ARM64.tar.gz >> ytstats_${{ github.event.release.tag_name }}_checksums.txt
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ytstats_${{ github.event.release.tag_name }}_checksums.txt
          ytstats_${{ github.event.release.tag_name }}_Windows-64bit.zip
          ytstats_${{ github.event.release.tag_name }}_Windows-ARM.zip
          ytstats_${{ github.event.release.tag_name }}_Windows-ARM64.zip
          ytstats_${{ github.event.release.tag_name }}_Linux-64bit.tar.gz
          ytstats_${{ github.event.release.tag_name }}_Linux-32bit.tar.gz
          ytstats_${{ github.event.release.tag_name }}_Linux-ARM.tar.gz
          ytstats_${{ github.event.release.tag_name }}_Linux-ARM64.tar.gz
          ytstats_${{ github.event.release.tag_name }}_macOS-64bit.tar.gz
          ytstats_${{ github.event.release.tag_name }}_macOS-ARM64.tar.gz
